node {
   def commit_id
   stage('Preparation') {
     checkout scm
     /* extracts the sha id, used to tag the image */
     sh "git rev-parse --short HEAD > .git/commit-id"
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
    /* we will use the nodejs that we added to jenkins */
     nodejs(nodeJSInstallationName: 'nodejs') {
      /* check the package.json file to see the install options */
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       def app = docker.build("moussena1992/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
